### ISSUE TITLE
load data from lmdb problem

### ISSUE THREAD

**Issue by leoliuf** [kyamagu/matlab-lmdb#10]
Hi kyamagu,
First at the most, this is a very nice work!!
I want to save some 3D matrix into lmdb database. I was able to do it with database.put('MyMatrix', MyMatrix) without any problem. I was also able to retrieve the data back by using MyMatrix2=database.get('MyMatrix'). However, the problem is the retrieved MyMatrix2 is a array of char while the saved MyMatrix is a matrix of int16. Let's say size(MyMatrix) == 256x256x32 (int16) then size(MyMatrix2) == 1x2097152 (char). Do I need to explicitly tell put() function the size of the data or did I just miss something important? Please help

**Comment by kyamagu** [comment]
@leoliuf Serialize/Deserialize data when using LMDB, e.g., using `num2str` and `str2double`. The database takes any binary in char format. See (Issue #3).

**Comment by kyamagu** [comment]
@leoliuf Also I have [this serialization package](https://github.com/kyamagu/matlab-serialization) if you need.

**Comment by leoliuf** [comment]
I tried this, it works like a charm!! Thanks again for this nice work

1) A (10x10x10 int16) -> serialize to B (1x2072 uint8)
2) database.put('B', B) 
3) B2=database.get('B') -> B2 (1x2072 char)
4) C=deserialize(uint8(B2)) -> C (10x10x10 int16)
