### ISSUE TITLE
try to convert the data to lmdb for caffe

### ISSUE THREAD

**Issue by whatcanisay-k** [kyamagu/matlab-lmdb#11]
After I run this command :
![qq 20161210170700](https://cloud.githubusercontent.com/assets/15904901/21072485/a175c900-beff-11e6-9b85-b4e11bb9eb39.jpg)

I cant not find this function caffe_pb.toDatum
Should I rebuild the caffe or what should I do

**Comment by kyamagu** [comment]
@zhangminwen That is only available in caffe-extension branch. i.e.,

    git checkout caffe-extension

**Comment by zhangminwen** [comment]
There is  another problem：
![qq 20161210221654](https://cloud.githubusercontent.com/assets/15904901/21073888/73ad492c-bf26-11e6-8185-c9c94afcbdf6.jpg)

and I use the solution like this:

![qq 20161210221722](https://cloud.githubusercontent.com/assets/15904901/21073896/8dfdc2e8-bf26-11e6-98f6-64a172df2aef.jpg)

but in the db.cpp , there is not a variable named LMDB_MAP_SIZE.

what should I do?
