### ISSUE TITLE
failed to make in windows enviroment

### ISSUE THREAD

**Issue by khcy82dyc** [kyamagu/matlab-lmdb#12]
Hi,
   Sorry to bother..I'm a windows user and I'm quite new to the terms unix, linux, shell, etc.
   I notice this is for UNIX but I thought to give it a try with 'MinGW make' through git bash under the matlab-lmdb-caffe-extension folder and got the following error msg. Just want to confirm if this is something to do with the cross-platform? Is there a quick solution to compile on windows?
Thanks!

$ make
C:/MinGW/bin/make -C src/liblmdb
make[1]: Entering directory 'C:/Projects/matlab-lmdb-caffe-extension/src/liblmdb'
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mdb_stat.o liblmdb.a  -o mdb_stat
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mdb_copy.o liblmdb.a  -o mdb_copy
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mdb_dump.o liblmdb.a  -o mdb_dump
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mdb_load.o liblmdb.a  -o mdb_load
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mtest.o liblmdb.a  -o mtest
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mtest2.o liblmdb.a  -o mtest2
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mtest3.o liblmdb.a  -o mtest3
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mtest4.o liblmdb.a  -o mtest4
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mtest5.o liblmdb.a  -o mtest5
make[1]: Leaving directory 'C:/Projects/matlab-lmdb-caffe-extension/src/liblmdb'
C:/MATLAB/R2016b/bin/mex.bat -output +lmdb/private/LMDB_.mexw64 src/LMDB_.cc -Iinclude -Isrc/liblmdb CXXFLAGS="\$CXXFLAGS -std=c++11" src/liblmdb/liblmdb.a
Building with 'MinGW64 Compiler (C++)'.
C:\Users\ding\AppData\Local\Temp\mex_8670067939871759_6064\LMDB_.obj:LMDB_.cc:(.text+0xe39): undefined reference to `mdb_txn_abort'
C:\Users\ding\AppData\Local\Temp\mex_8670067939871759_6064\LMDB_.obj:LMDB_.cc:(.text+0xe58): undefined reference to `mdb_txn_begin'
C:\Users\ding\AppData\Local\Temp\mex_8670067939871759_6064\LMDB_.obj:LMDB_.cc:(.text+0xe63): undefined reference to `mdb_strerror'
C:\Users\ding\AppData\Local\Temp\mex_8670067939871759_6064\LMDB_.obj:LMDB_.cc:(.text+0xe9e): undefined reference to `mdb_txn_abort'
C:\Users\ding\AppData\Local\Temp\mex_8670067939871759_6064\LMDB_.obj:LMDB_.cc:(.text+0xecf): undefined reference to `mdb_txn_abort'
C:\Users\ding\AppData\Local\Temp\mex_8670067939871759_6064\LMDB_.obj:LMDB_.cc:(.text+0xf07): undefined reference to `mdb_cursor_close'
C:\Users\ding\AppData\Local\Temp\mex_8670067939871759_6064\LMDB_.obj:LMDB_.cc:(.text+0xf1d): undefined reference to `mdb_cursor_open'
C:\Users\ding\AppData\Local\Temp\mex_8670067939871759_6064\LMDB_.obj:LMDB_.cc:(.text+0xf28): undefined reference to `mdb_strerror'
C:\Users\ding\AppData\Local\Temp\mex_8670067939871759_6064\LMDB_.obj:LMDB_.cc:(.text+0xf61): undefined reference to `mdb_txn_commit'
C:\Users\ding\AppData\Local\Temp\mex_8670067939871759_6064\LMDB_.obj:LMDB_.cc:(.text+0xf6c): undefined reference to `mdb_strerror'
C:\Users\ding\AppData\Local\Temp\mex_8670067939871759_6064\LMDB_.obj:LMDB_.cc:(.text+0xfbe): undefined reference to `mdb_dbi_close'
C:\Users\ding\AppData\Local\Temp\mex_8670067939871759_6064\LMDB_.obj:LMDB_.cc:(.text+0xfc7): undefined reference to `mdb_env_close'
C:\Users\ding\AppData\Local\Temp\mex_8670067939871759_6064\LMDB_.obj:LMDB_.cc:(.text+0x1007): undefined reference to `mdb_dbi_close'
...
...
...
...
...
...
collect2.exe: error: ld returned 1 exit status

Makefile:18: recipe for target '+lmdb/private/LMDB_.mexw64' failed
make: *** [+lmdb/private/LMDB_.mexw64] Error 127

**Comment by kyamagu** [comment]
@khcy82dyc This is a linker error. Is there `src/liblmdb/liblmdb.a`? Also check if your Matlab supports mingw environment for `mex`.

**Comment by khcy82dyc** [comment]
@kyamagu thanks a lot for the quick reply! I can confirm liblmdb.a is there, I've checked the mex environment in matlab is mingw and I've also manually tried to mex the c files in matlab:
mex src/LMDB_.cc -Iinclude -Isrc/liblmdb src/liblmdb/liblmdb.a
but..still got the error.

Could it be there was a problem generating the .a files? It generated lots of .a .o .so .exe files, but I also got lots of warning when I first time 'make' in mingw.

$ make
C:/MinGW/bin/make -C src/liblmdb
make[1]: Entering directory 'C:/Projects/matlab-lmdb-caffe-extension/src/liblmdb'
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   -c mdb.c
mdb.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /** @file mdb.c
 ^
mdb.c: In function 'mdb_strerror':
mdb.c:1354:35: warning: passing argument 7 of 'FormatMessageA' from incompatible pointer type [-Wincompatible-pointer-types]
   NULL, err, 0, ptr, sizeof(buf), pad);
                                   ^
In file included from c:\mingw\include\windows.h:44:0,
                 from mdb.c:40:
c:\mingw\include\winbase.h:1539:25: note: expected 'char **' but argument is of type 'char *'
 WINBASEAPI DWORD WINAPI FormatMessageA(DWORD,PCVOID,DWORD,DWORD,LPSTR,DWORD,va_list*);
                         ^
mdb.c: In function 'mdb_env_copyfd1':
mdb.c:8557:18: warning: implicit declaration of function '_aligned_malloc' [-Wimplicit-function-declaration]
  my.mc_wbuf[0] = _aligned_malloc(MDB_WBUF*2, env->me_os_psize);
                  ^
mdb.c:8557:16: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  my.mc_wbuf[0] = _aligned_malloc(MDB_WBUF*2, env->me_os_psize);
                ^
mdb.c:8585:21: warning: passing argument 3 of 'CreateThread' from incompatible pointer type [-Wincompatible-pointer-types]
  THREAD_CREATE(thr, mdb_env_copythr, &my);
                     ^
mdb.c:237:62: note: in definition of macro 'THREAD_CREATE'
 #define THREAD_CREATE(thr,start,arg) thr=CreateThread(NULL,0,start,arg,0,NULL)
                                                              ^
In file included from c:\mingw\include\windows.h:44:0,
                 from mdb.c:40:
c:\mingw\include\winbase.h:1424:26: note: expected 'LPTHREAD_START_ROUTINE' but argument is of type 'DWORD (*)(void *) {aka long unsigned int (*)(void *)}'
 WINBASEAPI HANDLE WINAPI CreateThread(LPSECURITY_ATTRIBUTES,DWORD,LPTHREAD_START_ROUTINE,PVOID,DWORD,PDWORD);
                          ^
mdb.c:8649:2: warning: implicit declaration of function '_aligned_free' [-Wimplicit-function-declaration]
  _aligned_free(my.mc_wbuf[0]);
  ^
mdb.c: In function 'mdb_strerror':
cc1.exe: warning: function may return address of local variable [-Wreturn-local-addr]
mdb.c:1322:7: note: declared here
  char buf[1024], *ptr = buf;
       ^
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   -c midl.c
midl.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /** @file midl.c
 ^
ar rs liblmdb.a mdb.o midl.o
ar: creating liblmdb.a
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized  -fPIC  -c mdb.c -o mdb.lo
mdb.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /** @file mdb.c
 ^
mdb.c: In function 'mdb_strerror':
mdb.c:1354:35: warning: passing argument 7 of 'FormatMessageA' from incompatible pointer type [-Wincompatible-pointer-types]
   NULL, err, 0, ptr, sizeof(buf), pad);
                                   ^
In file included from c:\mingw\include\windows.h:44:0,
                 from mdb.c:40:
c:\mingw\include\winbase.h:1539:25: note: expected 'char **' but argument is of type 'char *'
 WINBASEAPI DWORD WINAPI FormatMessageA(DWORD,PCVOID,DWORD,DWORD,LPSTR,DWORD,va_list*);
                         ^
mdb.c: In function 'mdb_env_copyfd1':
mdb.c:8557:18: warning: implicit declaration of function '_aligned_malloc' [-Wimplicit-function-declaration]
  my.mc_wbuf[0] = _aligned_malloc(MDB_WBUF*2, env->me_os_psize);
                  ^
mdb.c:8557:16: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  my.mc_wbuf[0] = _aligned_malloc(MDB_WBUF*2, env->me_os_psize);
                ^
mdb.c:8585:21: warning: passing argument 3 of 'CreateThread' from incompatible pointer type [-Wincompatible-pointer-types]
  THREAD_CREATE(thr, mdb_env_copythr, &my);
                     ^
mdb.c:237:62: note: in definition of macro 'THREAD_CREATE'
 #define THREAD_CREATE(thr,start,arg) thr=CreateThread(NULL,0,start,arg,0,NULL)
                                                              ^
In file included from c:\mingw\include\windows.h:44:0,
                 from mdb.c:40:
c:\mingw\include\winbase.h:1424:26: note: expected 'LPTHREAD_START_ROUTINE' but argument is of type 'DWORD (*)(void *) {aka long unsigned int (*)(void *)}'
 WINBASEAPI HANDLE WINAPI CreateThread(LPSECURITY_ATTRIBUTES,DWORD,LPTHREAD_START_ROUTINE,PVOID,DWORD,PDWORD);
                          ^
mdb.c:8649:2: warning: implicit declaration of function '_aligned_free' [-Wimplicit-function-declaration]
  _aligned_free(my.mc_wbuf[0]);
  ^
mdb.c: In function 'mdb_strerror':
cc1.exe: warning: function may return address of local variable [-Wreturn-local-addr]
mdb.c:1322:7: note: declared here
  char buf[1024], *ptr = buf;
       ^
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized  -fPIC  -c midl.c -o midl.lo
midl.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /** @file midl.c
 ^
gcc  -pthread -shared -o liblmdb.so mdb.lo midl.lo
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   -c mdb_stat.c
mdb_stat.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* mdb_stat.c - memory-mapped database status tool */
 ^
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mdb_stat.o liblmdb.a  -o mdb_stat
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   -c mdb_copy.c
mdb_copy.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* mdb_copy.c - memory-mapped database backup tool */
 ^
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mdb_copy.o liblmdb.a  -o mdb_copy
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   -c mdb_dump.c
mdb_dump.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* mdb_dump.c - memory-mapped database dump tool */
 ^
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mdb_dump.o liblmdb.a  -o mdb_dump
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   -c mdb_load.c
mdb_load.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* mdb_load.c - memory-mapped database load tool */
 ^
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mdb_load.o liblmdb.a  -o mdb_load
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   -c mtest.c
mtest.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* mtest.c - memory-mapped database tester/toy */
 ^
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mtest.o liblmdb.a  -o mtest
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   -c mtest2.c
mtest2.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* mtest2.c - memory-mapped database tester/toy */
 ^
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mtest2.o liblmdb.a  -o mtest2
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   -c mtest3.c
mtest3.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* mtest3.c - memory-mapped database tester/toy */
 ^
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mtest3.o liblmdb.a  -o mtest3
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   -c mtest4.c
mtest4.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* mtest4.c - memory-mapped database tester/toy */
 ^
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mtest4.o liblmdb.a  -o mtest4
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   -c mtest5.c
mtest5.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* mtest5.c - memory-mapped database tester/toy */
 ^
gcc -fPIC -pthread -O2 -g -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized   mtest5.o liblmdb.a  -o mtest5
make[1]: Leaving directory 'C:/Projects/matlab-lmdb-caffe-extension/src/liblmdb'
C:/MATLAB/R2016b/bin/mex.bat -output +lmdb/private/LMDB_.mexw64 src/LMDB_.cc -Iinclude -Isrc/liblmdb CXXFLAGS="\$CXXFLAGS -std=c++11" src/liblmdb/liblmdb.a
Building with 'MinGW64 Compiler (C++)'.
C:\Users\ding\AppData\Local\Temp\mex_8722688440267764_10428\LMDB_.obj:LMDB_.cc:(.text+0xe39): undefined reference to `mdb_txn_abort'
C:\Users\ding\AppData\Local\Temp\mex_8722688440267764_10428\LMDB_.obj:LMDB_.cc:(.text+0xe58): undefined reference to `mdb_txn_begin'
C:\Users\ding\AppData\Local\Temp\mex_8722688440267764_10428\LMDB_.obj:LMDB_.cc:(.text+0xe63): undefined reference to `mdb_strerror'

**Comment by kyamagu** [comment]
@khcy82dyc Very likely is that `mex.bat` is using different config from `gcc` in `make`, like 32-bit vs 64-bit. Maybe you can add a verbose flag (`-V`) in `mex` to check what build configuration is used there.

**Comment by khcy82dyc** [comment]
@kyamagu you are genius! i do have both 32b and 64b at the same time and problem solved after re-installation. however. I may need a little bit more help from you...
i'm now stuck at making caffe_pb, i think it might have to do with -lprotobuf..the error msg i got is:

make[1]: Leaving directory 'C:/Projects/matlab-lmdb-caffe-extension/src/liblmdb'
C:/MATLAB/R2016b/bin/mex.bat -output +caffe_pb/private/caffe_pb_.mexw64 src/caffe_pb_.cc -Iinclude -Isrc/liblmdb CXXFLAGS="\$CXXFLAGS -std=c++11" -IC:/Projects/caffe/build/src/caffe/proto -IC:/Projects/caffe/build/include/caffe/proto C:/Projects/caffe/build/src/caffe/proto.dir/Release/caffe.pb.obj -lprotobuf
MEX cannot find library 'protobuf' specified with the -l option.

 if I delete it I get:  C:/Projects/caffe/build/include/caffe/proto/caffe.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory

is it I need to install protobuf or something?

thank you so much for your time and sorry to bother you!

**Comment by kyamagu** [comment]
@khcy82dyc For caffe-extension, you need [the protobuf library](https://github.com/google/protobuf). [See this](http://stackoverflow.com/questions/9243816/how-to-build-googles-protobuf-in-windows-using-mingw).

**Comment by khcy82dyc** [comment]
@kyamagu so sorry I'm still here..I'm still trying to get it compiled..now the new error is: 


make[1]: Leaving directory 'C:/Projects/matlab-lmdb-caffe-extension/src/liblmdb'
C:/MATLAB/R2016b/bin/mex.bat -output +caffe_pb/private/caffe_pb_.mexw64 src/caffe_pb_.cc -Iinclude -Isrc/liblmdb CXXFLAGS="\$CXXFLAGS -std=c++11" -IC:/Projects/caffe/build/src/caffe/proto -IC:/Projects/caffe/build/include/caffe/proto C:/Projects/caffe/build/src/caffe/proto.dir/Release/caffe.pb.obj
Building with 'MinGW64 Compiler (C++)'.
Warning: corrupt .drectve at end of def file
C:\Users\ding\AppData\Local\Temp\mex_8996799659210473_11140\caffe_pb_.obj:caffe_pb_.cc:(.text+0x4b9): undefined reference to `caffe::Datum::Datum()'
C:\Users\ding\AppData\Local\Temp\mex_8996799659210473_11140\caffe_pb_.obj:caffe_pb_.cc:(.text+0x619): undefined reference to `google::protobuf::MessageLite::SerializeAsString() const'
C:\Users\ding\AppData\Local\Temp\mex_8996799659210473_11140\caffe_pb_.obj:caffe_pb_.cc:(.text+0x68b): undefined reference to `caffe::Datum::~Datum()'

...
..
..
..
..
thousands of similiar error message like those
..
...
..
..
..
...
C:/Projects/caffe/build/src/caffe/proto.dir/Release/caffe.pb.obj:(.rdata[??_7PReLUParameter@caffe@@6B@]+0x48): undefined reference to `?InitializationErrorString@Message@protobuf@google@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ'
C:/Projects/caffe/build/src/caffe/proto.dir/Release/caffe.pb.obj:(.rdata[??_7PReLUParameter@caffe@@6B@]+0x50): undefined reference to `?CheckTypeAndMergeFrom@Message@protobuf@google@@UEAAXAEBVMessageLite@23@@Z'
C:/Projects/caffe/build/src/caffe/proto.dir/Release/caffe.pb.obj:(.rdata[??_7PReLUParameter@caffe@@6B@]+0xa0): undefined reference to `?DiscardUnknownFields@Message@protobuf@google@@UEAAXXZ'
C:/Projects/caffe/build/src/caffe/proto.dir/Release/caffe.pb.obj:(.rdata[??_7PReLUParameter@caffe@@6B@]+0xa8): undefined reference to `?SpaceUsed@Message@protobuf@google@@UEBAHXZ'
C:/Projects/caffe/build/src/caffe/proto.dir/Release/caffe.pb.obj:(.data$r+0x0): undefined reference to `??_7type_info@@6B@'
collect2.exe: error: ld returned 1 exit status

makefile:26: recipe for target '+caffe_pb/private/caffe_pb_.mexw64' failed
make: *** [+caffe_pb/private/caffe_pb_.mexw64] Error 127
 
  
 .
.
.
.
.
.
do you think this is a linker error, or might be 32bit and 64bit error?
Thank you so much!!!

**Comment by khcy82dyc** [comment]
@kyamagu AHA, after so many days of trying out different things I have finally compiled it on Windows. the solution is to mex LMDB_ with mingw 4.9.2, then mex -setup and switch to visual studio and mex caffe.pd_
I think this is probably due to building caffe with VS at the beginning, since there was only two optionss VS and python on caffe's installation manual.
Anyway thanks a lot!
