### ISSUE TITLE
Problem with clear cursor

### ISSUE THREAD

**Issue by rodrigodebem** [kyamagu/matlab-lmdb#9]
Hi, 

I am having a problem when I clear a cursor. I have put it as a field in a Matlab struct and, for some reason, when I call clear cursor; and the method below is execute the 'txn_commit' and the 'txn_delete' functions are making the Matlab to crash. If I comment both lines it finishes my script correctly. 

Is there any drawback of commenting these lines? I am not sure what why they are being executed after the 'cursor_delete' one. 

Do you have any idea about what is wrong with it? Btw, thanks for the nice package.

  function delete(this)
  %DELETE Destructor.
    assert(isscalar(this));
    LMDB_('cursor_delete', this.id_);
    %LMDB_('txn_commit', this.transaction_id_);
    %LMDB_('txn_delete', this.transaction_id_);
  end

**Comment by kyamagu** [comment]
@rodrigodebem Are you keeping the struct with cursor? If you copy a handle object somewhere, you need to clear all of them; i.e.,

```matlab
    s.cursor = cursor;
    clear cursor;
    clear s;  % Don't forget this
```

**Comment by rodrigodebem** [comment]
Well, I guess this is exactly the problem, for example if I execute the following sequence even in the Matlab command line, it crashes when I execute the last line. May you could try yourself to double check.

>> db(1).readonly_db = lmdb.DB('./path/lmdb-data', 'RDONLY', true);
>> db(1).cursor = db(1).readonly_db.cursor('RDONLY', true);
>> clear db(1).cursor;
>> clear db(1).readonly_db;
>> clear db;

**Comment by kyamagu** [comment]
@rodrigodebem The issue could be that the last `clear db` is called, the order of clear for subfields are undefined. That's probably the reason. The easiest fix is to avoid using struct at all. Any handle objects are not really designed to be saved inside a struct.

**Comment by rodrigodebem** [comment]
@kyamagu Do you think the same rule applies for cell arrays?

**Comment by kyamagu** [comment]
@rodrigodebem The same is true for cell arrays. In general, handle for external resources (e.g., file pointer) should not be kept in a container unless you understand the risk.

There could be some mechanism to detect an invalid pointer after release in MEX. This will require dependency between pointers and could be tricky, though.

**Comment by rodrigodebem** [comment]
@kyamagu It seems I've found a way around the problem. Apparently even after the clear command a reference of the cursor and for the database is kept in the struct, as can be seen below. 

K>> db(1)
ans = 
      readonly_db: [1x1 lmdb.DB]
           cursor: [1x1 lmdb.Cursor]

So the follow sequence seems to work fine:

clear db(1).cursor;
db(1).cursor = [];
clear db(1).readonly_db;
db(1).readonly_db = [];
clear db;

Even if a reference is let in the Matlab ans variable it can cause a crash afterwards.

Thanks for the help!
